"""Stakeholder report generator — Phase 3 intelligence layer.

Produces an 8-section executive-ready report from experiment results. Claude
generates sections 1–7 via tool_use; section 8 (Technical Appendix) is always
programmatic. A grounding validator runs after generation to catch recommendation
inconsistencies and flag p-value leakage into non-technical sections.

Exports:
    ReportSection        — one section of the report
    StakeholderReport    — full assembled report dataclass
    generate_report      — async: call Claude and assemble the report
    build_fallback_report — sync: template-based report, no Claude needed
"""

from __future__ import annotations

import json
import logging
import re
import time
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Literal

import anthropic

from app.core.config import settings
from app.intelligence.interpreter import FullAnalysisResult, MLAnalysisSummary

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

PROMPT_VERSION = "reporter_v1"
CLAUDE_MODEL = "claude-sonnet-4-6"
TIMEOUT_SECONDS = 45.0

_COST_PER_INPUT_TOKEN = 3.0 / 1_000_000
_COST_PER_OUTPUT_TOKEN = 15.0 / 1_000_000

_SYSTEM_PROMPT: str = (
    Path(__file__).parent / "prompts" / "reporter_v1.txt"
).read_text(encoding="utf-8")

_SECTION_TITLES: dict[int, str] = {
    1: "Executive Summary",
    2: "Business Impact",
    3: "What We Tested",
    4: "Results",
    5: "Who It Worked For",
    6: "Concerns",
    7: "Recommendation",
    8: "Technical Appendix",
}

# Regex that catches common p-value / jargon patterns in sections 1-7
_PVALUE_PATTERN = re.compile(
    r"\bp[\s]*[=<>!]+\s*0\.\d+"  # p=0.03, p < 0.05, p>0.001
    r"|\bp-value\b"
    r"|\bz-statistic\b"
    r"|\bz-score\b"
    r"|\bz-test\b"
    r"|\bt-statistic\b"
    r"|\balpha\s*=\s*0\.\d+"
    r"|\bbeta\s*=\s*0\.\d+"
    r"|\bnull hypothesis\b",
    re.IGNORECASE,
)

# ---------------------------------------------------------------------------
# Data models
# ---------------------------------------------------------------------------


@dataclass
class ReportSection:
    """One section of the stakeholder report.

    Attributes:
        section_number: 1–8.
        title: Human-readable section title.
        content: Markdown-formatted section body.
        is_ai_generated: True for sections 1–7; False for section 8.
        data_sources: Fields from stats/ML results used to build this section.
    """

    section_number: int
    title: str
    content: str
    is_ai_generated: bool
    data_sources: list[str]


@dataclass
class StakeholderReport:
    """Fully assembled stakeholder report.

    Attributes:
        title: Report title derived from experiment name.
        generated_at: UTC timestamp of generation.
        prompt_version: Prompt constant version used (e.g. "reporter_v1").
        sections: All 8 report sections in order.
        markdown_content: Full report as a single Markdown string.
        html_content: Full report as a minimal HTML document.
        key_metric: The single number an executive will remember.
        recommendation: SHIP / DO_NOT_SHIP / EXTEND / INVESTIGATE.
        confidence_level: High / Medium / Low.
        confidence_reasoning: One-sentence explanation of confidence level.
        word_count: Word count of sections 1–7 only (not the appendix).
        ai_generated_sections: Section titles generated by Claude.
        programmatic_sections: Section titles built by code.
    """

    title: str
    generated_at: datetime
    prompt_version: str
    sections: list[ReportSection]
    markdown_content: str
    html_content: str
    key_metric: str
    recommendation: Literal["SHIP", "DO_NOT_SHIP", "EXTEND", "INVESTIGATE"]
    confidence_level: Literal["High", "Medium", "Low"]
    confidence_reasoning: str
    word_count: int
    ai_generated_sections: list[str]
    programmatic_sections: list[str]


# ---------------------------------------------------------------------------
# Claude tool schema
# ---------------------------------------------------------------------------

_TOOL_SCHEMA: dict[str, Any] = {
    "name": "write_experiment_report",
    "description": (
        "Write a structured stakeholder experiment report. "
        "ALWAYS call this tool — never respond in plain text. "
        "Return all seven narrative sections plus the recommendation metadata. "
        "Section 8 (Technical Appendix) is handled by code — do not write it."
    ),
    "input_schema": {
        "type": "object",
        "properties": {
            "section_1": {
                "type": "string",
                "description": (
                    "Executive Summary: 2–3 sentences. Verdict, key metric, recommendation. "
                    "No statistical jargon. If INVALID, lead with the warning."
                ),
            },
            "section_2": {
                "type": "string",
                "description": (
                    "Business Impact: Translate lift to business terms. "
                    "Use revenue figures only if daily_revenue is provided. "
                    "Include confidence interval in plain language."
                ),
            },
            "section_3": {
                "type": "string",
                "description": (
                    "What We Tested: Plain English description of treatment, audience, "
                    "duration, and user counts."
                ),
            },
            "section_4": {
                "type": "string",
                "description": (
                    "Results: Key findings in plain language. Include lift and significance. "
                    "FORBIDDEN: p-value, p=, z-statistic, z-score, alpha, beta."
                ),
            },
            "section_5": {
                "type": "string",
                "description": (
                    "Who It Worked For: Segment and HTE findings. "
                    "If no segment data: write exactly 'Segment analysis was not run "
                    "for this experiment.' Never fabricate."
                ),
            },
            "section_6": {
                "type": "string",
                "description": (
                    "Concerns: All data quality and validity issues honestly stated. "
                    "If clean: 'No data quality issues were detected.' Never skip."
                ),
            },
            "section_7": {
                "type": "string",
                "description": (
                    "Recommendation: One of SHIP/DO_NOT_SHIP/EXTEND/INVESTIGATE with "
                    "3–5 sentences of reasoning and concrete next steps."
                ),
            },
            "recommendation": {
                "type": "string",
                "enum": ["SHIP", "DO_NOT_SHIP", "EXTEND", "INVESTIGATE"],
                "description": "Must match the recommendation in section_7.",
            },
            "confidence_level": {
                "type": "string",
                "enum": ["High", "Medium", "Low"],
                "description": (
                    "High: significant, clean, stable. "
                    "Medium: significant but with caveats. "
                    "Low: not significant, invalid, or novelty detected."
                ),
            },
            "confidence_reasoning": {
                "type": "string",
                "description": "One sentence explaining the confidence level.",
            },
            "key_metric": {
                "type": "string",
                "description": (
                    "The single number an executive will remember. "
                    "Examples: '+18% conversion lift (significant)', "
                    "'No significant effect detected (lift: +2.1%)', "
                    "'Results invalid — do not act'."
                ),
            },
        },
        "required": [
            "section_1",
            "section_2",
            "section_3",
            "section_4",
            "section_5",
            "section_6",
            "section_7",
            "recommendation",
            "confidence_level",
            "confidence_reasoning",
            "key_metric",
        ],
    },
}


# ---------------------------------------------------------------------------
# User prompt construction
# ---------------------------------------------------------------------------


def _build_user_message(
    experiment_name: str,
    stats: FullAnalysisResult,
    ml: MLAnalysisSummary,
    daily_traffic: int | None,
    daily_revenue: float | None,
) -> str:
    """Construct the grounded user message sent to Claude.

    All numerical values are injected explicitly so Claude never needs to
    invent or estimate any figure.
    """
    lines: list[str] = [
        f"Experiment: {experiment_name}",
        "",
        "=== DATA SECTION (use these values exactly — do not invent other numbers) ===",
        "",
        "STATISTICAL RESULTS:",
        f"  is_significant: {stats.is_significant}",
        f"  lift_pct (relative lift, %): {stats.lift_pct:+.4f}",
        f"  lift_abs (absolute lift): {stats.lift_abs:+.6f}",
        f"  overall_recommendation: {stats.overall_recommendation}",
    ]

    if stats.warnings:
        lines.append(f"  stats_warnings: {'; '.join(stats.warnings)}")

    lines += [
        "",
        "ML VALIDITY:",
        f"  overall_verdict: {ml.overall_verdict}",
        f"  can_trust_results: {ml.can_trust_results}",
        f"  ml_recommendation: {ml.recommendation}",
    ]

    if ml.anomaly_validity:
        lines.append(f"  anomaly_validity: {ml.anomaly_validity}")
    if ml.novelty_pattern:
        lines.append(f"  novelty_pattern: {ml.novelty_pattern}")

    if ml.hte_top_modifier:
        modifier_clean = ml.hte_top_modifier.replace("_x_treat", "")
        lines.append(f"  hte_top_modifier: {modifier_clean}")
        if ml.hte_ate is not None:
            lines.append(f"  hte_ate: {ml.hte_ate:+.4f}")
        if ml.hte_business_recommendation:
            lines.append(f"  hte_recommendation: {ml.hte_business_recommendation}")

    if ml.responsive_segments is not None:
        lines.append(f"  responsive_segments: {ml.responsive_segments}")
    if ml.segment_recommendation:
        lines.append(f"  segment_recommendation: {ml.segment_recommendation}")

    if ml.key_insights:
        lines += ["", "KEY INSIGHTS FROM ML ENGINE:"]
        for insight in ml.key_insights:
            lines.append(f"  - {insight}")

    lines.append("")
    lines.append("CONTEXT:")
    if daily_traffic is not None:
        lines.append(f"  daily_traffic: {daily_traffic} users/day")
    if daily_revenue is not None:
        lines.append(f"  daily_revenue: ${daily_revenue:,.2f}")
    else:
        lines.append("  daily_revenue: not provided — do NOT invent revenue figures")

    lines += [
        "",
        "=== END DATA SECTION ===",
        "",
        "Write the experiment report following the structure in your instructions.",
        "Use the exact numerical values from the DATA SECTION above.",
        "Sections 1–7 only — section 8 is generated by code.",
    ]

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Section 8 — Technical Appendix (always programmatic)
# ---------------------------------------------------------------------------


def _build_section_8(
    stats: FullAnalysisResult,
    ml: MLAnalysisSummary,
) -> ReportSection:
    """Build the technical appendix from raw result values — no AI involved.

    This section is the only place where p-values, test statistics, and
    raw module outputs appear. It is always marked is_ai_generated=False.
    """
    lines: list[str] = [
        "### Statistical Results",
        "",
        "| Field | Value |",
        "|---|---|",
        f"| Statistically significant | {'Yes' if stats.is_significant else 'No'} |",
        f"| Relative lift | {stats.lift_pct:+.4f}% |",
        f"| Absolute lift | {stats.lift_abs:+.6f} |",
        f"| p-value | {stats.p_value:.6f} |",
        f"| Engine recommendation | {stats.overall_recommendation} |",
    ]

    if stats.warnings:
        lines += [
            "",
            "**Statistical warnings:**",
        ]
        for w in stats.warnings:
            lines.append(f"- {w}")

    lines += [
        "",
        "### ML Module Results",
        "",
        "| Module | Validity / Pattern |",
        "|---|---|",
    ]

    if ml.anomaly_validity:
        lines.append(f"| Anomaly detection | {ml.anomaly_validity} |")
    else:
        lines.append("| Anomaly detection | skipped |")

    if ml.novelty_pattern:
        lines.append(f"| Novelty detection | {ml.novelty_pattern} |")
    else:
        lines.append("| Novelty detection | skipped |")

    if ml.hte_top_modifier:
        modifier_clean = ml.hte_top_modifier.replace("_x_treat", "")
        ate_str = f"{ml.hte_ate:+.4f}" if ml.hte_ate is not None else "N/A"
        lines.append(f"| HTE top modifier | {modifier_clean} (ATE={ate_str}) |")
    else:
        lines.append("| HTE | skipped or no top modifier |")

    if ml.responsive_segments is not None:
        lines.append(f"| Responsive segments | {ml.responsive_segments} |")
    else:
        lines.append("| Segment analysis | skipped |")

    lines += [
        "",
        "### Overall ML Verdict",
        "",
        f"**Verdict:** {ml.overall_verdict}  ",
        f"**Can trust results:** {'Yes' if ml.can_trust_results else 'No'}  ",
        f"**ML recommendation:** {ml.recommendation}",
        "",
        "### Generation Metadata",
        "",
        f"| Field | Value |",
        "|---|---|",
        f"| Prompt version | {PROMPT_VERSION} |",
        f"| Model | {CLAUDE_MODEL} |",
    ]

    if ml.key_insights:
        lines += [
            "",
            "### ML Key Insights",
            "",
        ]
        for insight in ml.key_insights:
            lines.append(f"- {insight}")

    return ReportSection(
        section_number=8,
        title=_SECTION_TITLES[8],
        content="\n".join(lines),
        is_ai_generated=False,
        data_sources=[
            "stats_result.p_value",
            "stats_result.lift_pct",
            "stats_result.lift_abs",
            "stats_result.is_significant",
            "ml_result.overall_verdict",
            "ml_result.anomaly_validity",
            "ml_result.novelty_pattern",
        ],
    )


# ---------------------------------------------------------------------------
# Grounding validator
# ---------------------------------------------------------------------------


def _validate_grounding(
    tool_output: dict[str, Any],
    stats: FullAnalysisResult,
    ml: MLAnalysisSummary,
    daily_revenue: float | None,
) -> dict[str, Any]:
    """Validate and fix inconsistencies in Claude's tool output.

    Fixes recommendation mismatches in-place. Logs warnings for p-value
    leakage and business-impact errors but does not modify section text.

    Args:
        tool_output: Raw dict from Claude's write_experiment_report tool call.
        stats: Statistical results used for consistency checks.
        ml: ML results used for consistency checks.
        daily_revenue: If provided, validates business impact arithmetic.

    Returns:
        Possibly-modified tool_output dict.
    """
    rec: str = tool_output.get("recommendation", "")

    # Fix recommendation inconsistencies
    if rec == "SHIP" and not ml.can_trust_results:
        logger.warning(
            "grounding: SHIP recommended but can_trust_results=False — overriding to INVESTIGATE"
        )
        tool_output["recommendation"] = "INVESTIGATE"
        rec = "INVESTIGATE"

    if rec == "SHIP" and ml.novelty_pattern in ("NOVELTY", "LEARNING"):
        logger.warning(
            "grounding: SHIP recommended with novelty_pattern=%s — overriding to EXTEND",
            ml.novelty_pattern,
        )
        tool_output["recommendation"] = "EXTEND"
        rec = "EXTEND"

    if rec == "SHIP" and not stats.is_significant:
        logger.warning(
            "grounding: SHIP recommended but is_significant=False — overriding to EXTEND"
        )
        tool_output["recommendation"] = "EXTEND"
        rec = "EXTEND"

    # Check for p-value mentions in sections 1–7
    for i in range(1, 8):
        section_key = f"section_{i}"
        content = tool_output.get(section_key, "")
        if _PVALUE_PATTERN.search(content):
            logger.warning(
                "grounding: statistical jargon (p-value/z-score) detected in %s", section_key
            )

    # Validate business impact arithmetic when daily_revenue is available
    if daily_revenue is not None and stats.is_significant:
        expected_monthly = abs(stats.lift_pct / 100.0) * daily_revenue * 30
        section_2 = tool_output.get("section_2", "")
        # Extract any dollar figures from section 2
        dollar_matches = re.findall(r"\$[\d,]+(?:\.\d+)?", section_2)
        for match in dollar_matches:
            val = float(match.replace("$", "").replace(",", ""))
            # Flag if the stated monthly figure is off by more than 50%
            if val > 1000 and abs(val - expected_monthly) / max(expected_monthly, 1) > 0.5:
                logger.warning(
                    "grounding: business impact $%.0f in section_2 differs from "
                    "expected $%.0f by >50%%",
                    val,
                    expected_monthly,
                )
                break

    # Validate key_metric is non-empty
    if not tool_output.get("key_metric", "").strip():
        if stats.is_significant:
            tool_output["key_metric"] = f"{stats.lift_pct:+.1f}% lift (significant)"
        else:
            tool_output["key_metric"] = (
                f"No significant effect (lift: {stats.lift_pct:+.1f}%)"
            )
        logger.warning("grounding: key_metric was empty — substituted from stats data")

    return tool_output


# ---------------------------------------------------------------------------
# Markdown / HTML assembly
# ---------------------------------------------------------------------------


def _assemble_markdown(
    experiment_name: str,
    sections: list[ReportSection],
    report_meta: dict[str, Any],
) -> str:
    """Combine all sections into a single Markdown document."""
    lines: list[str] = [
        f"# Experiment Report: {experiment_name}",
        "",
        f"**Generated:** {report_meta['generated_at'].strftime('%Y-%m-%d %H:%M UTC')}  ",
        f"**Recommendation:** {report_meta['recommendation']}  ",
        f"**Confidence:** {report_meta['confidence_level']}  ",
        f"**Key metric:** {report_meta['key_metric']}",
        "",
        "---",
        "",
    ]

    for section in sections:
        lines.append(f"## {section.section_number}. {section.title}")
        lines.append("")
        lines.append(section.content)
        lines.append("")

    return "\n".join(lines)


def _assemble_html(markdown_content: str) -> str:
    """Convert the assembled Markdown to a minimal HTML document.

    Handles: h1/h2/h3, bold, bullet lists, horizontal rules, paragraphs.
    Intentionally minimal — no external library dependency.
    """
    html = markdown_content

    # Escape HTML special chars that appear in table pipes etc. before conversion
    # Headers (order matters: h3 before h2 before h1)
    html = re.sub(r"^### (.+)$", r"<h3>\1</h3>", html, flags=re.MULTILINE)
    html = re.sub(r"^## (.+)$", r"<h2>\1</h2>", html, flags=re.MULTILINE)
    html = re.sub(r"^# (.+)$", r"<h1>\1</h1>", html, flags=re.MULTILINE)

    # Bold
    html = re.sub(r"\*\*(.+?)\*\*", r"<strong>\1</strong>", html)

    # Horizontal rule
    html = re.sub(r"^---$", "<hr/>", html, flags=re.MULTILINE)

    # Markdown tables → pass through as pre-formatted
    # (complex; leave as-is inside a <pre> block)
    lines = html.split("\n")
    out: list[str] = []
    in_list = False
    in_table = False

    for line in lines:
        stripped = line.strip()

        # Detect table rows
        if stripped.startswith("|") and stripped.endswith("|"):
            if not in_table:
                out.append("<table>")
                in_table = True
            # Skip separator rows (|---|---|)
            if re.match(r"^\|[-| ]+\|$", stripped):
                continue
            cells = [c.strip() for c in stripped.strip("|").split("|")]
            out.append(
                "<tr>" + "".join(f"<td>{c}</td>" for c in cells) + "</tr>"
            )
            continue
        else:
            if in_table:
                out.append("</table>")
                in_table = False

        # Bullet lists
        if stripped.startswith("- ") or stripped.startswith("* "):
            if not in_list:
                out.append("<ul>")
                in_list = True
            out.append(f"<li>{stripped[2:]}</li>")
            continue
        else:
            if in_list:
                out.append("</ul>")
                in_list = False

        # Already-converted HTML tags pass through
        if stripped.startswith("<") or not stripped:
            out.append(line)
        else:
            out.append(f"<p>{line}</p>")

    if in_list:
        out.append("</ul>")
    if in_table:
        out.append("</table>")

    body = "\n".join(out)
    return (
        "<!DOCTYPE html>\n<html lang=\"en\">\n<head><meta charset=\"utf-8\">"
        "<title>Experiment Report</title></head>\n<body>\n"
        f"{body}\n</body>\n</html>"
    )


def _count_words(sections: list[ReportSection]) -> int:
    """Count words across sections 1–7 only (not the appendix)."""
    text = " ".join(
        s.content for s in sections if s.section_number < 8
    )
    return len(text.split())


# ---------------------------------------------------------------------------
# DB logging
# ---------------------------------------------------------------------------


async def _log_to_db(
    db: Any,
    *,
    experiment_id: Any,
    experiment_name: str,
    tool_output_json: str,
    input_tokens: int,
    output_tokens: int,
    duration_ms: int,
) -> None:
    """Write a row to ai_interactions. Fails silently so reporting is never blocked."""
    if db is None:
        return
    try:
        from app.models.experiment import AIInteraction, InteractionType

        cost = (
            input_tokens * _COST_PER_INPUT_TOKEN
            + output_tokens * _COST_PER_OUTPUT_TOKEN
        )
        record = AIInteraction(
            experiment_id=experiment_id,
            interaction_type=InteractionType.report,
            user_prompt=experiment_name,
            ai_response=tool_output_json,
            tokens_used=input_tokens + output_tokens,
            prompt_version=PROMPT_VERSION,
            input_tokens=input_tokens,
            output_tokens=output_tokens,
            estimated_cost_usd=cost,
            duration_ms=duration_ms,
        )
        db.add(record)
        await db.flush()
    except Exception as exc:
        logger.warning("Failed to log report interaction to DB: %s", exc)


# ---------------------------------------------------------------------------
# Core report generation function
# ---------------------------------------------------------------------------


async def generate_report(
    experiment_name: str,
    stats_result: FullAnalysisResult,
    ml_result: MLAnalysisSummary,
    daily_traffic: int | None = None,
    daily_revenue: float | None = None,
    format: Literal["markdown", "html"] = "markdown",
    db: Any = None,
    experiment_id: Any = None,
) -> StakeholderReport:
    """Generate a stakeholder report from experiment results.

    Calls Claude via tool_use to generate sections 1–7. Section 8 is always
    built programmatically. A grounding validator checks the recommendation
    and flags p-value leakage before the report is assembled.

    On Claude API failure, generates a complete programmatic fallback report
    (no AI, all sections from templates) and marks it clearly as a fallback.

    Args:
        experiment_name: Human-readable experiment name.
        stats_result: Statistical analysis output.
        ml_result: ML analysis summary (anomaly, novelty, HTE, segments).
        daily_traffic: Optional daily user count for context.
        daily_revenue: Optional daily revenue for business impact calculation.
        format: Preferred output format — both markdown_content and html_content
                are always generated regardless of this parameter.
        db: AsyncSession for logging. May be None in tests.
        experiment_id: UUID for DB logging. May be None.

    Returns:
        StakeholderReport with all 8 sections, full markdown, and HTML.
    """
    client = anthropic.AsyncAnthropic(api_key=settings.ANTHROPIC_API_KEY)
    user_message = _build_user_message(
        experiment_name, stats_result, ml_result, daily_traffic, daily_revenue
    )

    t0 = time.monotonic()
    try:
        response = await client.messages.create(
            model=CLAUDE_MODEL,
            max_tokens=2048,
            system=_SYSTEM_PROMPT,
            tools=[_TOOL_SCHEMA],
            tool_choice={"type": "tool", "name": "write_experiment_report"},
            messages=[{"role": "user", "content": user_message}],
            timeout=TIMEOUT_SECONDS,
        )
    except (anthropic.APITimeoutError, anthropic.APIError) as exc:
        logger.warning(
            "reporter: Claude API error for experiment=%r — generating fallback: %s",
            experiment_name,
            exc,
        )
        return build_fallback_report(
            experiment_name=experiment_name,
            stats_result=stats_result,
            ml_result=ml_result,
            daily_traffic=daily_traffic,
            daily_revenue=daily_revenue,
        )

    duration_ms = int((time.monotonic() - t0) * 1000)
    input_tokens: int = response.usage.input_tokens
    output_tokens: int = response.usage.output_tokens

    tool_block = next(
        (b for b in response.content if b.type == "tool_use"),
        None,
    )
    if tool_block is None:
        logger.warning(
            "reporter: no tool_use block returned for experiment=%r — generating fallback",
            experiment_name,
        )
        return build_fallback_report(
            experiment_name=experiment_name,
            stats_result=stats_result,
            ml_result=ml_result,
            daily_traffic=daily_traffic,
            daily_revenue=daily_revenue,
        )

    tool_output: dict[str, Any] = dict(tool_block.input)

    # Run grounding validator — fixes recommendation and logs issues
    tool_output = _validate_grounding(tool_output, stats_result, ml_result, daily_revenue)

    await _log_to_db(
        db,
        experiment_id=experiment_id,
        experiment_name=experiment_name,
        tool_output_json=json.dumps(tool_output),
        input_tokens=input_tokens,
        output_tokens=output_tokens,
        duration_ms=duration_ms,
    )

    # Build typed sections 1–7
    sections: list[ReportSection] = []
    for i in range(1, 8):
        key = f"section_{i}"
        content = tool_output.get(key, f"[Section {i} not generated]")
        sections.append(
            ReportSection(
                section_number=i,
                title=_SECTION_TITLES[i],
                content=content,
                is_ai_generated=True,
                data_sources=_section_data_sources(i),
            )
        )

    # Build section 8 — always programmatic
    sections.append(_build_section_8(stats_result, ml_result))

    recommendation: Literal["SHIP", "DO_NOT_SHIP", "EXTEND", "INVESTIGATE"] = (
        tool_output.get("recommendation", "INVESTIGATE")
    )
    confidence_level: Literal["High", "Medium", "Low"] = (
        tool_output.get("confidence_level", "Low")
    )

    now = datetime.now(timezone.utc)
    report_meta = {
        "generated_at": now,
        "recommendation": recommendation,
        "confidence_level": confidence_level,
        "key_metric": tool_output.get("key_metric", ""),
    }

    markdown_content = _assemble_markdown(experiment_name, sections, report_meta)
    html_content = _assemble_html(markdown_content)
    word_count = _count_words(sections)

    logger.info(
        "reporter: generated report experiment=%r recommendation=%s confidence=%s "
        "words=%d tokens_in=%d tokens_out=%d duration_ms=%d",
        experiment_name,
        recommendation,
        confidence_level,
        word_count,
        input_tokens,
        output_tokens,
        duration_ms,
    )

    return StakeholderReport(
        title=f"Experiment Report: {experiment_name}",
        generated_at=now,
        prompt_version=PROMPT_VERSION,
        sections=sections,
        markdown_content=markdown_content,
        html_content=html_content,
        key_metric=tool_output.get("key_metric", ""),
        recommendation=recommendation,
        confidence_level=confidence_level,
        confidence_reasoning=tool_output.get("confidence_reasoning", ""),
        word_count=word_count,
        ai_generated_sections=[_SECTION_TITLES[i] for i in range(1, 8)],
        programmatic_sections=[_SECTION_TITLES[8]],
    )


# ---------------------------------------------------------------------------
# Section data source registry
# ---------------------------------------------------------------------------


def _section_data_sources(section_number: int) -> list[str]:
    """Return the result fields that inform a given AI-generated section."""
    sources: dict[int, list[str]] = {
        1: ["stats_result.is_significant", "stats_result.lift_pct", "ml_result.overall_verdict"],
        2: ["stats_result.lift_pct", "stats_result.lift_abs", "daily_revenue"],
        3: ["experiment_name", "daily_traffic"],
        4: ["stats_result.is_significant", "stats_result.lift_pct", "stats_result.warnings"],
        5: ["ml_result.hte_top_modifier", "ml_result.responsive_segments"],
        6: [
            "ml_result.anomaly_validity",
            "ml_result.novelty_pattern",
            "ml_result.can_trust_results",
        ],
        7: [
            "stats_result.is_significant",
            "ml_result.can_trust_results",
            "ml_result.novelty_pattern",
            "ml_result.overall_verdict",
        ],
    }
    return sources.get(section_number, [])


# ---------------------------------------------------------------------------
# Programmatic fallback report
# ---------------------------------------------------------------------------


def build_fallback_report(
    experiment_name: str,
    stats_result: FullAnalysisResult,
    ml_result: MLAnalysisSummary,
    daily_traffic: int | None = None,
    daily_revenue: float | None = None,
) -> StakeholderReport:
    """Generate a complete report using only template logic — no Claude API.

    Called when the Claude API is unavailable. All 8 sections are programmatic.
    The report is clearly marked as a fallback in section 1.

    Args:
        experiment_name: Human-readable experiment name.
        stats_result: Statistical analysis output.
        ml_result: ML analysis summary.
        daily_traffic: Optional daily user count.
        daily_revenue: Optional daily revenue.

    Returns:
        StakeholderReport with all 8 sections, no AI content.
    """
    from app.intelligence.templates.fallback_report import build_fallback_sections

    sections_data = build_fallback_sections(
        experiment_name=experiment_name,
        stats=stats_result,
        ml=ml_result,
        daily_traffic=daily_traffic,
        daily_revenue=daily_revenue,
    )

    sections: list[ReportSection] = []
    for i in range(1, 8):
        sections.append(
            ReportSection(
                section_number=i,
                title=_SECTION_TITLES[i],
                content=sections_data[i],
                is_ai_generated=False,
                data_sources=_section_data_sources(i),
            )
        )
    sections.append(_build_section_8(stats_result, ml_result))

    recommendation = _derive_recommendation(stats_result, ml_result)
    confidence_level = _derive_confidence(stats_result, ml_result)

    if not stats_result.is_significant:
        key_metric = f"No significant effect (lift: {stats_result.lift_pct:+.1f}%)"
    elif not ml_result.can_trust_results:
        key_metric = "Results invalid — do not act"
    else:
        key_metric = f"{stats_result.lift_pct:+.1f}% lift (significant)"

    now = datetime.now(timezone.utc)
    report_meta = {
        "generated_at": now,
        "recommendation": recommendation,
        "confidence_level": confidence_level,
        "key_metric": key_metric,
    }

    markdown_content = _assemble_markdown(experiment_name, sections, report_meta)
    html_content = _assemble_html(markdown_content)
    word_count = _count_words(sections)

    return StakeholderReport(
        title=f"Experiment Report: {experiment_name}",
        generated_at=now,
        prompt_version=f"{PROMPT_VERSION}_fallback",
        sections=sections,
        markdown_content=markdown_content,
        html_content=html_content,
        key_metric=key_metric,
        recommendation=recommendation,
        confidence_level=confidence_level,
        confidence_reasoning="AI unavailable — report generated from templates.",
        word_count=word_count,
        ai_generated_sections=[],
        programmatic_sections=[_SECTION_TITLES[i] for i in range(1, 9)],
    )


def _derive_recommendation(
    stats: FullAnalysisResult,
    ml: MLAnalysisSummary,
) -> Literal["SHIP", "DO_NOT_SHIP", "EXTEND", "INVESTIGATE"]:
    """Deterministic recommendation from results — mirrors grounding validator logic."""
    if not ml.can_trust_results:
        return "INVESTIGATE"
    if ml.novelty_pattern in ("NOVELTY", "LEARNING"):
        return "EXTEND"
    if not stats.is_significant:
        return "DO_NOT_SHIP"
    if ml.overall_verdict == "NEEDS_REVIEW":
        return "SHIP"
    return "SHIP"


def _derive_confidence(
    stats: FullAnalysisResult,
    ml: MLAnalysisSummary,
) -> Literal["High", "Medium", "Low"]:
    """Deterministic confidence level from results."""
    if not ml.can_trust_results or not stats.is_significant:
        return "Low"
    if ml.novelty_pattern in ("NOVELTY", "LEARNING") or ml.overall_verdict == "NEEDS_REVIEW":
        return "Medium"
    return "High"
