import { useParams, Link } from 'react-router-dom'
import { Download, ArrowLeft, Zap } from 'lucide-react'
import PageShell from '../components/layout/PageShell'
import Button from '../components/ui/Button'
import Card from '../components/ui/Card'
import Badge from '../components/ui/Badge'
import LoadingSpinner from '../components/ui/LoadingSpinner'

const SECTIONS = [
  'Executive Summary',
  'Experiment Design',
  'Statistical Analysis',
  'Segment Analysis',
  'Risk Assessment',
  'Business Impact',
  'Recommendation',
  'Technical Appendix',
]

const MOCK_REPORT = {
  'exp-001': {
    name: 'Checkout Button Colour',
    result: 'significant',
    generated: true,
    sections: {
      'Executive Summary': 'Changing the checkout CTA from grey to blue drove a statistically significant +12.4% increase in checkout conversion (p = 0.003). Over 14 days across 24,580 subjects, the blue button consistently outperformed the control. We recommend shipping the variant.',
      'Recommendation': 'Ship the blue button to 100% of traffic. Expected annualised revenue impact: +£240K at current conversion volumes. No guardrail metrics were harmed (session duration, bounce rate both within normal range).',
    },
  },
}

export default function ExperimentReport() {
  const { id } = useParams()
  const report = MOCK_REPORT[id]
  const expName = report?.name ?? id

  return (
    <PageShell
      breadcrumbs={[
        { label: 'Experiments', href: '/experiments' },
        { label: expName, href: `/experiments/${id}` },
        { label: 'Report' },
      ]}
      actions={
        <div className="flex items-center gap-2">
          <Link to={`/experiments/${id}`}>
            <Button variant="ghost" size="sm">
              <ArrowLeft size={13} />
              Results
            </Button>
          </Link>
          <Button variant="secondary" size="sm">
            <Download size={13} />
            Export PDF
          </Button>
        </div>
      }
    >
      {/* Header */}
      <div className="mb-8">
        <div className="flex items-center gap-2 mb-3">
          <Zap size={14} className="text-blue" />
          <span className="text-xs text-secondary uppercase tracking-widest font-medium">
            AI Stakeholder Report
          </span>
          {report?.generated && <Badge variant="completed" label="Generated" />}
        </div>
        <h1 className="font-display text-2xl font-bold text-primary mb-1">{expName}</h1>
        <p className="text-secondary text-sm">
          Eight-section analysis generated by Claude · Requires human review before distribution.
        </p>
      </div>

      {/* Section navigation */}
      <div className="flex gap-2 flex-wrap mb-8">
        {SECTIONS.map((s, i) => (
          <button
            key={s}
            className="text-[11px] px-2.5 py-1 rounded border border-subtle text-secondary hover:text-primary hover:border-active transition-colors"
          >
            {i + 1}. {s}
          </button>
        ))}
      </div>

      {/* Report sections */}
      <div className="space-y-4 max-w-3xl">
        {SECTIONS.map((section, i) => {
          const content = report?.sections?.[section]
          const isReady = !!content

          return (
            <Card key={section} className="p-6">
              <div className="flex items-center justify-between mb-4">
                <h2 className="font-display font-bold text-[15px] text-primary">
                  <span className="text-muted font-mono text-sm mr-2">{String(i + 1).padStart(2, '0')}</span>
                  {section}
                </h2>
                {!isReady && (
                  <div className="flex items-center gap-2 text-xs text-secondary">
                    <LoadingSpinner size={12} />
                    Generating
                  </div>
                )}
              </div>

              {isReady ? (
                <p className="text-secondary text-sm leading-relaxed">{content}</p>
              ) : (
                <div className="space-y-2">
                  <div className="h-3 bg-elevated rounded animate-shimmer"
                    style={{ background: 'linear-gradient(90deg, var(--color-bg-card) 25%, var(--color-bg-elevated) 50%, var(--color-bg-card) 75%)', backgroundSize: '200% 100%' }} />
                  <div className="h-3 bg-elevated rounded w-4/5 animate-shimmer"
                    style={{ background: 'linear-gradient(90deg, var(--color-bg-card) 25%, var(--color-bg-elevated) 50%, var(--color-bg-card) 75%)', backgroundSize: '200% 100%' }} />
                  <div className="h-3 bg-elevated rounded w-3/5 animate-shimmer"
                    style={{ background: 'linear-gradient(90deg, var(--color-bg-card) 25%, var(--color-bg-elevated) 50%, var(--color-bg-card) 75%)', backgroundSize: '200% 100%' }} />
                </div>
              )}
            </Card>
          )
        })}
      </div>

      {/* Review gate */}
      <div className="mt-8 p-5 border border-amber rounded-lg max-w-3xl"
        style={{ backgroundColor: 'rgba(245,158,11,0.05)' }}>
        <p className="text-sm text-secondary mb-3">
          <span className="font-medium text-amber">Human review required</span> — AI-generated reports must be
          reviewed before external distribution. Verify key figures against the raw stats.
        </p>
        <div className="flex gap-2">
          <Button variant="secondary" size="sm">Request Review</Button>
          <Button size="sm">Approve &amp; Share</Button>
        </div>
      </div>
    </PageShell>
  )
}
